apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.exposePort }}
      targetPort: {{ .Values.targetPort }}
      protocol: TCP
      name: http-port
  selector:
      app: {{ .Values.appName }}

